import React from "react";

export function ReportTemplateCard({ title, desc, icon, onPreview }) {
  return (
    <div
      className="card"
      style={{ padding: "20px", display: "flex", flexDirection: "column", gap: "16px" }}
    >
      <div style={{ display: "flex", alignItems: "center", gap: "12px" }}>
        <div
          style={{
            width: "40px",
            height: "40px",
            borderRadius: "var(--radius-sm)",
            backgroundColor: "var(--color-blue-50)",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
          }}
        >
          <span
            className="material-symbols-rounded icon-filled"
            style={{ color: "var(--color-blue-600)" }}
          >
            {icon}
          </span>
        </div>
        <div>
          <h3 style={{ margin: 0, fontSize: "15px", fontWeight: 600 }}>{title}</h3>
          <p style={{ margin: 0, fontSize: "13px", color: "var(--color-text-secondary)" }}>
            {desc}
          </p>
        </div>
      </div>
      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "8px" }}>
        <button
          className="btn btn-primary"
          onClick={onPreview}
          style={{ gridColumn: "1 / -1", height: "36px" }}
        >
          <span className="material-symbols-rounded" style={{ fontSize: "18px" }}>
            visibility
          </span>{" "}
          Preview
        </button>
        <button className="btn btn-secondary" style={{ fontSize: "12px", height: "32px" }}>
          <span className="material-symbols-rounded" style={{ fontSize: "16px" }}>
            picture_as_pdf
          </span>{" "}
          PDF
        </button>
        <button className="btn btn-secondary" style={{ fontSize: "12px", height: "32px" }}>
          <span className="material-symbols-rounded" style={{ fontSize: "16px" }}>
            table
          </span>{" "}
          CSV
        </button>
        <button
          className="btn btn-secondary"
          style={{ gridColumn: "1 / -1", fontSize: "12px", height: "32px" }}
        >
          <span className="material-symbols-rounded" style={{ fontSize: "16px" }}>
            data_object
          </span>{" "}
          JSON
        </button>
      </div>
    </div>
  );
}

export function ReportHistory() {
  const history = [
    {
      id: "REP-104",
      name: "Weekly Exec Summary",
      date: "Oct 12, 2025",
      user: "SYSTEM",
      status: "Ready",
    },
    {
      id: "REP-103",
      name: "Monthly Threat Rollup",
      date: "Oct 01, 2025",
      user: "admin@co.com",
      status: "Ready",
    },
    {
      id: "REP-102",
      name: "Compliance Audit - Q3",
      date: "Sep 30, 2025",
      user: "secops@co.com",
      status: "Ready",
    },
    {
      id: "REP-101",
      name: "DLP Violation Log",
      date: "Sep 25, 2025",
      user: "asmith@co.com",
      status: "Archived",
    },
  ];

  return (
    <div className="card" style={{ flex: 1, display: "flex", flexDirection: "column" }}>
      <h2 className="heading-2" style={{ margin: "0 0 16px 0", fontSize: "15px" }}>
        Report History
      </h2>
      <div style={{ display: "flex", flexDirection: "column", gap: "8px", overflowY: "auto" }}>
        {history.map((item) => (
          <div
            key={item.id}
            style={{
              display: "flex",
              justifyContent: "space-between",
              alignItems: "center",
              padding: "12px",
              backgroundColor: "var(--color-surface-hover)",
              borderRadius: "var(--radius-sm)",
              border: "1px solid var(--color-border-light)",
            }}
          >
            <div>
              <div
                style={{ fontSize: "13px", fontWeight: 600, color: "var(--color-text-primary)" }}
              >
                {item.name}
              </div>
              <div
                style={{ fontSize: "11px", color: "var(--color-text-tertiary)", marginTop: "2px" }}
              >
                Generated by {item.user} • {item.date}
              </div>
            </div>
            <div style={{ display: "flex", gap: "8px" }}>
              <button className="btn-icon" title="Download PDF">
                <span className="material-symbols-rounded" style={{ fontSize: "18px" }}>
                  download
                </span>
              </button>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

export function ReportViewer({ reportType }) {
  if (!reportType) {
    return (
      <div
        style={{
          flex: 1,
          backgroundColor: "var(--color-bg-base)",
          borderRadius: "var(--radius-md)",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          color: "var(--color-text-tertiary)",
        }}
      >
        <div style={{ textAlign: "center" }}>
          <span
            className="material-symbols-rounded"
            style={{ fontSize: "48px", marginBottom: "16px", opacity: 0.5 }}
          >
            assignment
          </span>
          <p>Select a report template to generate a preview.</p>
        </div>
      </div>
    );
  }

  // Google Docs style Viewer
  return (
    <div
      style={{
        flex: 1,
        backgroundColor: "var(--color-bg-base)",
        borderRadius: "var(--radius-md)",
        border: "1px solid var(--color-border)",
        overflowY: "auto",
        display: "flex",
        justifyContent: "center",
        padding: "40px 24px",
      }}
    >
      {/* "A4 Paper" Container */}
      <div
        style={{
          width: "100%",
          maxWidth: "700px",
          backgroundColor: "white",
          boxShadow: "0 4px 12px rgba(0,0,0,0.1)",
          padding: "60px 48px",
          minHeight: "800px",
          display: "flex",
          flexDirection: "column",
          fontFamily: '"Times New Roman", Times, serif',
          color: "#202124",
        }}
      >
        {/* Document Header */}
        <div
          style={{
            borderBottom: "2px solid #202124",
            paddingBottom: "16px",
            marginBottom: "32px",
            display: "flex",
            justifyContent: "space-between",
            alignItems: "flex-end",
          }}
        >
          <div>
            <h1 style={{ margin: 0, fontSize: "24px", fontWeight: "bold" }}>
              {reportType} Security Report
            </h1>
            <p style={{ margin: "4px 0 0 0", fontSize: "12px", color: "#5f6368" }}>
              USB Device Control & Monitoring Framework
            </p>
          </div>
          <div style={{ textAlign: "right" }}>
            <div style={{ fontSize: "12px" }}>
              Date: <strong>October 12, 2025</strong>
            </div>
            <div style={{ fontSize: "12px", marginTop: "4px" }}>
              Generated By: <strong>SYSTEM ADMIN</strong>
            </div>
          </div>
        </div>

        {/* Document Body */}
        <h2
          style={{
            fontSize: "16px",
            borderBottom: "1px solid #dadce0",
            paddingBottom: "4px",
            marginBottom: "16px",
          }}
        >
          1. Executive Summary
        </h2>
        <p
          style={{ fontSize: "14px", lineHeight: 1.6, marginBottom: "24px", textAlign: "justify" }}
        >
          This report provides a comprehensive overview of hardware interface security for the
          requested period. The USB Device Control system successfully intercepted{" "}
          <strong>14 unauthorized storage devices</strong>, preventing potential Data Loss
          Prevention (DLP) violations. All authorized peripheral activity remained within
          established baseline metrics.
        </p>

        <h2
          style={{
            fontSize: "16px",
            borderBottom: "1px solid #dadce0",
            paddingBottom: "4px",
            marginBottom: "16px",
          }}
        >
          2. Threat Interceptions
        </h2>
        <table
          style={{
            width: "100%",
            borderCollapse: "collapse",
            fontSize: "13px",
            marginBottom: "32px",
          }}
        >
          <thead>
            <tr
              style={{
                backgroundColor: "#f1f3f4",
                borderTop: "1px solid #202124",
                borderBottom: "1px solid #202124",
              }}
            >
              <th style={{ padding: "8px", textAlign: "left" }}>Event ID</th>
              <th style={{ padding: "8px", textAlign: "left" }}>Device Vendor</th>
              <th style={{ padding: "8px", textAlign: "left" }}>Host</th>
              <th style={{ padding: "8px", textAlign: "right" }}>Action Taken</th>
            </tr>
          </thead>
          <tbody>
            <tr style={{ borderBottom: "1px solid #dadce0" }}>
              <td style={{ padding: "8px", fontFamily: "monospace" }}>EVT-4401</td>
              <td style={{ padding: "8px" }}>SanDisk Cruzer</td>
              <td style={{ padding: "8px", fontFamily: "monospace" }}>WIN-LPT-21</td>
              <td
                style={{ padding: "8px", textAlign: "right", fontWeight: "bold", color: "#d93025" }}
              >
                Blocked
              </td>
            </tr>
            <tr style={{ borderBottom: "1px solid #dadce0" }}>
              <td style={{ padding: "8px", fontFamily: "monospace" }}>EVT-4402</td>
              <td style={{ padding: "8px" }}>Generic HID (BadUSB)</td>
              <td style={{ padding: "8px", fontFamily: "monospace" }}>WIN-DESK-04</td>
              <td
                style={{ padding: "8px", textAlign: "right", fontWeight: "bold", color: "#d93025" }}
              >
                Quarantine
              </td>
            </tr>
            <tr style={{ borderBottom: "1px solid #dadce0" }}>
              <td style={{ padding: "8px", fontFamily: "monospace" }}>EVT-4403</td>
              <td style={{ padding: "8px" }}>Kingston DT50</td>
              <td style={{ padding: "8px", fontFamily: "monospace" }}>SRV-BACKUP-01</td>
              <td
                style={{ padding: "8px", textAlign: "right", fontWeight: "bold", color: "#188038" }}
              >
                Allowed
              </td>
            </tr>
          </tbody>
        </table>

        <h2
          style={{
            fontSize: "16px",
            borderBottom: "1px solid #dadce0",
            paddingBottom: "4px",
            marginBottom: "16px",
          }}
        >
          3. Analyst Remarks
        </h2>
        <div
          style={{
            border: "1px solid #dadce0",
            padding: "16px",
            backgroundColor: "#f8f9fa",
            fontSize: "14px",
            lineHeight: 1.6,
            fontStyle: "italic",
          }}
        >
          No persistent threats detected. Proceed with standard patching cycle for Q4.
        </div>

        {/* Footer Signatures */}
        <div
          style={{
            marginTop: "auto",
            display: "flex",
            justifyContent: "space-between",
            paddingTop: "64px",
          }}
        >
          <div style={{ width: "250px", borderTop: "1px solid #202124", paddingTop: "8px" }}>
            <div style={{ fontSize: "12px", fontWeight: "bold" }}>
              Security Operations Center (SOC)
            </div>
            <div style={{ fontSize: "12px", color: "#5f6368" }}>Reviewer Signature</div>
          </div>
          <div style={{ width: "250px", borderTop: "1px solid #202124", paddingTop: "8px" }}>
            <div style={{ fontSize: "12px", fontWeight: "bold" }}>
              Chief Information Security Officer
            </div>
            <div style={{ fontSize: "12px", color: "#5f6368" }}>Approval Signature</div>
          </div>
        </div>
      </div>
    </div>
  );
}
